"""create presence table

Revision ID: 73b614580132
Revises: 0c8f3dc1b61e
Create Date: 2026-04-13 11:24:07.173422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b614580132'
down_revision: Union[str, Sequence[str], None] = '0c8f3dc1b61e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presence',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), server_default='idle', nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_index(op.f('ix_challenge_participants_ranking'), table_name='challenge_participants')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_challenge_participants_ranking'), 'challenge_participants', ['challenge_id', sa.literal_column('score DESC')], unique=False)
    op.drop_table('presence')
    # ### end Alembic commands ###
