"""add avatar_url and height_cm to profiles

Revision ID: c8b07ea5fba4
Revises: eb3abd2af58d
Create Date: 2026-03-23 11:12:49.374834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b07ea5fba4'
down_revision: Union[str, Sequence[str], None] = 'eb3abd2af58d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('height_cm', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'avatar_url')
    op.drop_column('profiles', 'height_cm')
    # ### end Alembic commands ###
