"""sincronizar_columna_id_en_profiles

Revision ID: 8ddb208b5d22
Revises: edc3b35fab95
Create Date: 2026-03-11 00:28:07.196473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ddb208b5d22'
down_revision: Union[str, Sequence[str], None] = 'edc3b35fab95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('profiles', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('profiles', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('goal', sa.String(length=500), nullable=True))
    op.alter_column('profiles', 'weight_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_username'), table_name='profiles')
    op.drop_column('profiles', 'username')
    op.drop_column('profiles', 'last_name')
    op.drop_column('profiles', 'height_cm')
    op.drop_column('profiles', 'first_name')
    op.drop_column('profiles', 'user_id')
    op.drop_column('profiles', 'fitness_goal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('fitness_goal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('height_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_profiles_username'), 'profiles', ['username'], unique=True)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    op.alter_column('profiles', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('profiles', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'weight_kg',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('profiles', 'goal')
    op.drop_column('profiles', 'display_name')
    op.drop_column('profiles', 'id')
    op.drop_table('sessions')
    # ### end Alembic commands ###
